### PR TITLE
Resolves organizations to get code.

### LINKED ISSUE #206: AdminMetadata bf:source (which will become bf:assigner) provides incorrect label in MARC conversion
**Type of change**
This is a change/reported defect.

**Example RDF records**
Please provide URIs or RDF of the `bf:Instance`. If providing RDF, Turtle is preferred.
https://api.stage.sinopia.io/resource/879212bf-f815-489f-abc5-b9882d74fb12

**Resource template**
Which resource template does this apply to? In which Sinopia environment (development, stage, production)?
pcc:bf2:AdminMetadata in the pcc:bf2:Monograph:Work and pcc:bf2:Monograph:Instance templates
image
This image shows what the user gets in the lookup

**Expected MARC**
What MARC did you expect to receive?

040 $a CSt $b eng $c CSt $e rda

**Actual MARC**
What MARC did you actually receive (if mapped incorrectly)?

040 $a cst $b eng $c cst $e rda

Note the lack of correct capitalization. This is important in this coding

**Expected mapping logic**
Please describe the logic of the mapping.

Value from the LOC cultural heritage institutions should be take from 
<skos:notation rdf:datatype="http://id.loc.gov/datatypes/orgs/code">xx</skos:notation> 
rather than 
<skos:notation rdf:datatype="http://id.loc.gov/datatypes/orgs/normalized"> xx</skos:notation> or the end of the URI if that is how it is currently done.

Closely linked to issue xxx

### PR DESCRIPTION
**Pull request by justinlittman**
closes #206

## Why was this change made?
Per @NancyL 

## How was this change tested?
Unit

### CODE REVIEW

File: lib/rdf2marc/resolver/cultural_heritage_institution.rb [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+  module Resolver
+    CODE_DATATYPE_URI = RDF::URI('http://id.loc.gov/datatypes/orgs/code')
+
+    # Resolver for cultural heritage organization codes from id.loc.gov
+    class CulturalHeritageInstitution
+      def self.resolve_code(uri)
+        graph = RDF::Graph.load("#{uri}.skos.nt")
+        query = GraphQuery.new(graph)
+        notation_terms = query.path_all([SKOS.notation], subject_term: RDF::URI.new(uri))
+        notation_terms.select { |term| term.is_a?(RDF::Literal) && term.datatype == CODE_DATATYPE_URI }.first&.value
```
Comment (jcoyne) [inline lib/rdf2marc/resolver/cultural_heritage_institution.rb:13]: Rather than `select { ... }.first` can you use `find { ...}` here?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: lib/rdf2marc/resolver/cultural_heritage_institution.rb (hunk 1 above)
Comment (justinlittman) [reply lib/rdf2marc/resolver/cultural_heritage_institution.rb]: Definitely. Fixed.

**Review by jcoyne — APPROVED** [review]
