### PR TITLE
Fixed dupe tests.

### LINKED ISSUE #69: Fix tests in leader_spec
For  model2marc/leader_spec.rb, implement two tests (lines 74 encoding level and line 94 cataloging form) labeled as “to be implemented”.

This is fallout from adding rubocop-respec.

### PR DESCRIPTION
**Pull request by justinlittman**
closes #69

### CODE REVIEW

File: spec/rdf2marc/rdf2model/mappers/leader_spec.rb [hunk 1]
```diff
@@ -89,30 +88,8 @@
...
-        <#{admin_metadata_term}> <http://id.loc.gov/ontologies/bflc/encodingLevel> <http://id.loc.gov/vocabulary/menclvl/f>.
-        <http://id.loc.gov/vocabulary/menclvl/f> <http://www.w3.org/2000/01/rdf-schema#label> "full".
-      TTL
-    end
-
-    let(:model) do
-      {
-        bibliographic_level: 'item',
-        type: 'language_material',
-        encoding_level: 'full'
```
Comment (ndushay) [inline spec/rdf2marc/rdf2model/mappers/leader_spec.rb:107]: I do wonder what cataloging form is and if we never wrote the test right for it ...

**Review by ndushay — APPROVED** [review]

File: spec/rdf2marc/rdf2model/mappers/leader_spec.rb (hunk 1 above)
Comment (justinlittman) [reply spec/rdf2marc/rdf2model/mappers/leader_spec.rb:107]: Cataloging form is the same as description conventions, which is tested below. I fixed the label of this test.

So now everything should be tested and labeled correctly. Thanks for pushing on this.
